package br.com.ifpb.teste.model;

public enum TipoDeMembro {

	PRESIDENTE("PRESIDENTE"), DOCENTE_INTERNO("DOCENTE_INTERNO"),  TECNICO_ADMINISTRATIVO_PEDAGOGICO("TECNICO_ADMINISTRATIVO_PEDAGOGICO"),
	DOCENTE_EXTERNO("DOCENTE_EXTERNO"), DISCENTE("DISCENTE"),  SUPLENTE_DISCENTE("SUPLENTE_DISCENTE"),
	SUPLENTE_TECNICO_ADMINISTRATIVO_PEDAGOGICO("SUPLENTE_TECNICO_ADMINISTRATIVO_PEDAGOGICO"),
	SUPLENTE_DOCENTE_EXTERNO("SUPLENTE_DOCENTE_EXTERNO");

	private String nome;
	
	private TipoDeMembro(String nome) {
		this.nome = nome;
	}
	
	public String getNome() {
		return nome;
	}

}
